# kube-prometheus-stack default overrides

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.example.com # replace with your domain
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.example.com # replace with your domain

grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.example.com # replace with your domain
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.example.com # replace with your domain
  adminUser: admin
  adminPassword: prom-operator
  persistence:
    enabled: true
    size: 5Gi
  dashboards:
    default:
      k8s-overview.json:
        file: ../manifests/dashboards/k8s-overview.json
      pod-performance.json:
        file: ../manifests/dashboards/pod-performance.json
