apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack
  namespace: monitoring
type: Opaque
stringData:
  slack-webhook-url: "<YOUR_SLACK_WEBHOOK_URL>" # Replace with your actual Slack webhook URL
